/**
 * HTML Report Generator - Creates interactive static HTML reports.
 */

import type { InterviewResult, ToolProfile } from '../interview/types.js';
import type { MCPTool } from '../transport/types.js';

/**
 * Generate a complete HTML report from interview results.
 */
export function generateHtmlReport(result: InterviewResult): string {
  const { discovery, toolProfiles, summary, limitations, recommendations, metadata } = result;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(discovery.serverInfo.name)} - Inquest Report</title>
  <style>
${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${escapeHtml(discovery.serverInfo.name)}</h1>
      <p class="subtitle">Generated by <a href="https://github.com/dotsetlabs/inquest">Inquest</a> on ${formatDate(metadata.startTime)}</p>
    </header>

    <nav class="nav">
      <a href="#overview" class="nav-link">Overview</a>
      <a href="#tools" class="nav-link">Tools</a>
      ${result.workflowResults && result.workflowResults.length > 0 ? '<a href="#workflows" class="nav-link">Workflows</a>' : ''}
      <a href="#findings" class="nav-link">Findings</a>
      <a href="#security" class="nav-link">Security</a>
    </nav>

    <main>
      <!-- Overview Section -->
      <section id="overview" class="section">
        <h2>Overview</h2>
        <p class="summary">${escapeHtml(summary)}</p>

        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-value">${toolProfiles.length}</div>
            <div class="stat-label">Tools</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">${metadata.toolCallCount}</div>
            <div class="stat-label">Tool Calls</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">${metadata.errorCount}</div>
            <div class="stat-label">Errors</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">${formatDuration(metadata.durationMs)}</div>
            <div class="stat-label">Duration</div>
          </div>
        </div>

        <div class="info-grid">
          <div class="info-item">
            <span class="info-label">Server Version:</span>
            <span class="info-value">${escapeHtml(discovery.serverInfo.version)}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Protocol Version:</span>
            <span class="info-value">${escapeHtml(discovery.protocolVersion)}</span>
          </div>
          <div class="info-item">
            <span class="info-label">Model:</span>
            <span class="info-value">${escapeHtml(metadata.model)}</span>
          </div>
          ${metadata.personas && metadata.personas.length > 0 ? `
          <div class="info-item">
            <span class="info-label">Personas:</span>
            <span class="info-value">${metadata.personas.map(p => escapeHtml(p.name)).join(', ')}</span>
          </div>
          ` : ''}
        </div>

        <h3>Capabilities</h3>
        <div class="capabilities">
          ${discovery.capabilities.tools ? '<span class="capability enabled">Tools</span>' : '<span class="capability disabled">Tools</span>'}
          ${discovery.capabilities.prompts ? '<span class="capability enabled">Prompts</span>' : '<span class="capability disabled">Prompts</span>'}
          ${discovery.capabilities.resources ? '<span class="capability enabled">Resources</span>' : '<span class="capability disabled">Resources</span>'}
          ${discovery.capabilities.logging ? '<span class="capability enabled">Logging</span>' : '<span class="capability disabled">Logging</span>'}
        </div>
      </section>

      <!-- Tools Section -->
      <section id="tools" class="section">
        <h2>Tools</h2>

        <div class="search-bar">
          <input type="text" id="tool-search" placeholder="Search tools..." onkeyup="filterTools()">
        </div>

        <div id="tools-list" class="tools-grid">
${generateToolCards(discovery.tools, toolProfiles)}
        </div>
      </section>

      <!-- Workflows Section -->
${result.workflowResults && result.workflowResults.length > 0 ? generateWorkflowsSection(result) : ''}

      <!-- Findings Section -->
      <section id="findings" class="section">
        <h2>Findings</h2>

        <div class="filter-bar">
          <label>
            <input type="checkbox" id="filter-behavior" checked onchange="filterFindings()"> Behavior
          </label>
          <label>
            <input type="checkbox" id="filter-limitations" checked onchange="filterFindings()"> Limitations
          </label>
          <label>
            <input type="checkbox" id="filter-security" checked onchange="filterFindings()"> Security
          </label>
        </div>

        <table class="findings-table" id="findings-table">
          <thead>
            <tr>
              <th onclick="sortTable(0)">Tool ↕</th>
              <th onclick="sortTable(1)">Category ↕</th>
              <th onclick="sortTable(2)">Finding ↕</th>
            </tr>
          </thead>
          <tbody>
${generateFindingsRows(toolProfiles)}
          </tbody>
        </table>
      </section>

      <!-- Security Section -->
      <section id="security" class="section">
        <h2>Security Considerations</h2>
${generateSecuritySection(toolProfiles)}
      </section>

      <!-- Limitations Section -->
      ${limitations.length > 0 ? `
      <section id="limitations" class="section">
        <h2>Known Limitations</h2>
        <ul class="limitations-list">
          ${limitations.map(l => `<li>${escapeHtml(l)}</li>`).join('\n          ')}
        </ul>
      </section>
      ` : ''}

      <!-- Recommendations Section -->
      ${recommendations.length > 0 ? `
      <section id="recommendations" class="section">
        <h2>Recommendations</h2>
        <ul class="recommendations-list">
          ${recommendations.map(r => `<li>${escapeHtml(r)}</li>`).join('\n          ')}
        </ul>
      </section>
      ` : ''}
    </main>

    <footer class="footer">
      <p>Generated by <a href="https://github.com/dotsetlabs/inquest">Inquest</a> - MCP Server Behavioral Profiler</p>
      <p>Interview completed in ${formatDuration(metadata.durationMs)} with ${metadata.toolCallCount} tool calls</p>
    </footer>
  </div>

  <script>
${getScripts()}
  </script>
</body>
</html>`;
}

/**
 * Generate tool cards HTML.
 */
function generateToolCards(tools: MCPTool[], profiles: ToolProfile[]): string {
  return tools.map(tool => {
    const profile = profiles.find(p => p.name === tool.name);
    const hasWarnings = profile && (profile.securityNotes.length > 0 || profile.limitations.length > 0);
    const statusClass = hasWarnings ? 'has-warnings' : 'ok';

    return `          <div class="tool-card ${statusClass}" data-tool="${escapeHtml(tool.name)}">
            <div class="tool-header">
              <h3>${escapeHtml(tool.name)}</h3>
              <span class="tool-status ${statusClass}">${hasWarnings ? '⚠️' : '✓'}</span>
            </div>
            <p class="tool-description">${escapeHtml(tool.description || 'No description')}</p>
            ${profile ? `
            <div class="tool-stats">
              <span class="tool-stat">${profile.behavioralNotes.length} behaviors</span>
              <span class="tool-stat">${profile.limitations.length} limitations</span>
              <span class="tool-stat">${profile.securityNotes.length} security notes</span>
            </div>
            ` : ''}
            <button class="expand-btn" onclick="toggleToolDetails('${escapeHtml(tool.name)}')">Show Details</button>
            <div class="tool-details" id="details-${escapeHtml(tool.name)}" style="display: none;">
              ${tool.inputSchema ? `
              <h4>Input Schema</h4>
              <pre><code>${escapeHtml(JSON.stringify(tool.inputSchema, null, 2))}</code></pre>
              ` : ''}
              ${profile && profile.behavioralNotes.length > 0 ? `
              <h4>Observed Behavior</h4>
              <ul>${profile.behavioralNotes.map(n => `<li>${escapeHtml(n)}</li>`).join('')}</ul>
              ` : ''}
              ${profile && profile.limitations.length > 0 ? `
              <h4>Limitations</h4>
              <ul class="warning-list">${profile.limitations.map(l => `<li>${escapeHtml(l)}</li>`).join('')}</ul>
              ` : ''}
              ${profile && profile.securityNotes.length > 0 ? `
              <h4>Security Notes</h4>
              <ul class="security-list">${profile.securityNotes.map(s => `<li>${escapeHtml(s)}</li>`).join('')}</ul>
              ` : ''}
            </div>
          </div>`;
  }).join('\n');
}

/**
 * Generate workflows section HTML.
 */
function generateWorkflowsSection(result: InterviewResult): string {
  if (!result.workflowResults || result.workflowResults.length === 0) {
    return '';
  }

  const workflows = result.workflowResults.map(wr => {
    const statusClass = wr.success ? 'success' : 'failure';
    const statusIcon = wr.success ? '✅' : '❌';

    const stepsHtml = wr.steps.map((sr, i) => {
      const stepClass = sr.success ? 'step-success' : 'step-failure';
      return `<div class="workflow-step ${stepClass}">
                <span class="step-number">${i + 1}</span>
                <span class="step-tool">${escapeHtml(sr.step.tool)}</span>
                <span class="step-status">${sr.success ? '✓' : '✗'}</span>
                ${sr.analysis ? `<p class="step-analysis">${escapeHtml(sr.analysis)}</p>` : ''}
                ${sr.error ? `<p class="step-error">Error: ${escapeHtml(sr.error)}</p>` : ''}
              </div>`;
    }).join('\n');

    // Generate mermaid diagram
    const mermaidDiagram = generateMermaidDiagram(wr);

    return `<div class="workflow-card ${statusClass}">
            <div class="workflow-header">
              <h3>${statusIcon} ${escapeHtml(wr.workflow.name)}</h3>
            </div>
            <p class="workflow-description">${escapeHtml(wr.workflow.description)}</p>
            ${wr.summary ? `<blockquote class="workflow-summary">${escapeHtml(wr.summary)}</blockquote>` : ''}

            <div class="workflow-diagram">
              <pre class="mermaid">${mermaidDiagram}</pre>
            </div>

            <div class="workflow-steps">
              <h4>Steps</h4>
              ${stepsHtml}
            </div>
          </div>`;
  }).join('\n');

  return `      <section id="workflows" class="section">
        <h2>Workflows</h2>
        <div class="workflows-grid">
${workflows}
        </div>
      </section>`;
}

/**
 * Generate mermaid diagram for workflow.
 */
function generateMermaidDiagram(wr: InterviewResult['workflowResults'] extends (infer T)[] | undefined ? T : never): string {
  if (!wr) return '';

  let diagram = 'flowchart LR\n';

  for (let i = 0; i < wr.steps.length; i++) {
    const step = wr.steps[i];
    const nodeClass = step.success ? ':::success' : ':::failure';
    diagram += `    S${i}["${step.step.tool}"]${nodeClass}\n`;

    if (i < wr.steps.length - 1) {
      diagram += `    S${i} --> S${i + 1}\n`;
    }
  }

  diagram += '    classDef success fill:#90EE90\n';
  diagram += '    classDef failure fill:#FFB6C1\n';

  return diagram;
}

/**
 * Generate findings table rows.
 */
function generateFindingsRows(profiles: ToolProfile[]): string {
  const rows: string[] = [];

  for (const profile of profiles) {
    for (const note of profile.behavioralNotes) {
      rows.push(`            <tr class="finding-behavior">
              <td>${escapeHtml(profile.name)}</td>
              <td><span class="badge badge-behavior">Behavior</span></td>
              <td>${escapeHtml(note)}</td>
            </tr>`);
    }

    for (const limitation of profile.limitations) {
      rows.push(`            <tr class="finding-limitations">
              <td>${escapeHtml(profile.name)}</td>
              <td><span class="badge badge-limitation">Limitation</span></td>
              <td>${escapeHtml(limitation)}</td>
            </tr>`);
    }

    for (const secNote of profile.securityNotes) {
      rows.push(`            <tr class="finding-security">
              <td>${escapeHtml(profile.name)}</td>
              <td><span class="badge badge-security">Security</span></td>
              <td>${escapeHtml(secNote)}</td>
            </tr>`);
    }
  }

  return rows.join('\n');
}

/**
 * Generate security section HTML.
 */
function generateSecuritySection(profiles: ToolProfile[]): string {
  const findings: Array<{ tool: string; note: string; severity: string }> = [];

  for (const profile of profiles) {
    for (const note of profile.securityNotes) {
      const severity = classifySeverity(note);
      findings.push({ tool: profile.name, note, severity });
    }
  }

  if (findings.length === 0) {
    return '<p class="no-findings">No security considerations identified.</p>';
  }

  const critical = findings.filter(f => f.severity === 'critical');
  const warnings = findings.filter(f => f.severity === 'warning');
  const info = findings.filter(f => f.severity === 'info');

  let html = '';

  if (critical.length > 0) {
    html += `        <div class="security-group critical">
          <h3>Critical Issues</h3>
          <ul>
            ${critical.map(f => `<li><strong>${escapeHtml(f.tool)}:</strong> ${escapeHtml(f.note)}</li>`).join('\n            ')}
          </ul>
        </div>\n`;
  }

  if (warnings.length > 0) {
    html += `        <div class="security-group warning">
          <h3>Warnings</h3>
          <ul>
            ${warnings.map(f => `<li><strong>${escapeHtml(f.tool)}:</strong> ${escapeHtml(f.note)}</li>`).join('\n            ')}
          </ul>
        </div>\n`;
  }

  if (info.length > 0) {
    html += `        <div class="security-group info">
          <h3>Informational</h3>
          <ul>
            ${info.map(f => `<li><strong>${escapeHtml(f.tool)}:</strong> ${escapeHtml(f.note)}</li>`).join('\n            ')}
          </ul>
        </div>\n`;
  }

  return html;
}

/**
 * Classify security severity.
 */
function classifySeverity(note: string): 'critical' | 'warning' | 'info' {
  const lower = note.toLowerCase();

  if (['injection', 'rce', 'remote code', 'arbitrary code', 'command execution'].some(kw => lower.includes(kw))) {
    return 'critical';
  }

  if (['risk', 'vulnerab', 'dangerous', 'unsafe', 'leak', 'exposure'].some(kw => lower.includes(kw))) {
    return 'warning';
  }

  return 'info';
}

/**
 * Get CSS styles for the HTML report.
 */
function getStyles(): string {
  return `
    :root {
      --primary: #6366f1;
      --primary-dark: #4f46e5;
      --success: #22c55e;
      --warning: #f59e0b;
      --danger: #ef4444;
      --gray-50: #f9fafb;
      --gray-100: #f3f4f6;
      --gray-200: #e5e7eb;
      --gray-300: #d1d5db;
      --gray-600: #4b5563;
      --gray-800: #1f2937;
      --gray-900: #111827;
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--gray-50);
      color: var(--gray-800);
      line-height: 1.6;
    }

    .container { max-width: 1200px; margin: 0 auto; padding: 2rem; }

    .header {
      text-align: center;
      margin-bottom: 2rem;
      padding-bottom: 2rem;
      border-bottom: 1px solid var(--gray-200);
    }

    .header h1 { font-size: 2.5rem; color: var(--gray-900); }
    .subtitle { color: var(--gray-600); margin-top: 0.5rem; }
    .subtitle a { color: var(--primary); }

    .nav {
      display: flex;
      gap: 1rem;
      justify-content: center;
      margin-bottom: 2rem;
      flex-wrap: wrap;
    }

    .nav-link {
      padding: 0.5rem 1rem;
      background: white;
      border: 1px solid var(--gray-200);
      border-radius: 0.5rem;
      text-decoration: none;
      color: var(--gray-800);
      transition: all 0.2s;
    }

    .nav-link:hover { background: var(--primary); color: white; border-color: var(--primary); }

    .section {
      background: white;
      border-radius: 1rem;
      padding: 2rem;
      margin-bottom: 2rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }

    .section h2 {
      font-size: 1.5rem;
      margin-bottom: 1.5rem;
      padding-bottom: 0.5rem;
      border-bottom: 2px solid var(--primary);
    }

    .summary { font-size: 1.1rem; color: var(--gray-600); margin-bottom: 1.5rem; }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }

    .stat-card {
      background: var(--gray-50);
      padding: 1.5rem;
      border-radius: 0.5rem;
      text-align: center;
    }

    .stat-value { font-size: 2rem; font-weight: bold; color: var(--primary); }
    .stat-label { color: var(--gray-600); font-size: 0.875rem; }

    .info-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 0.5rem;
      margin-bottom: 1.5rem;
    }

    .info-item { padding: 0.5rem; background: var(--gray-50); border-radius: 0.25rem; }
    .info-label { font-weight: 600; color: var(--gray-600); }
    .info-value { color: var(--gray-800); }

    .capabilities { display: flex; gap: 0.5rem; flex-wrap: wrap; }

    .capability {
      padding: 0.25rem 0.75rem;
      border-radius: 9999px;
      font-size: 0.875rem;
    }

    .capability.enabled { background: #dcfce7; color: #166534; }
    .capability.disabled { background: var(--gray-100); color: var(--gray-600); }

    .search-bar { margin-bottom: 1.5rem; }

    .search-bar input {
      width: 100%;
      padding: 0.75rem 1rem;
      border: 1px solid var(--gray-200);
      border-radius: 0.5rem;
      font-size: 1rem;
    }

    .tools-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 1rem;
    }

    .tool-card {
      background: var(--gray-50);
      border: 1px solid var(--gray-200);
      border-radius: 0.75rem;
      padding: 1.5rem;
      transition: all 0.2s;
    }

    .tool-card:hover { box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    .tool-card.has-warnings { border-left: 4px solid var(--warning); }
    .tool-card.ok { border-left: 4px solid var(--success); }

    .tool-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
    .tool-header h3 { font-size: 1.125rem; color: var(--gray-900); }
    .tool-status.has-warnings { color: var(--warning); }
    .tool-status.ok { color: var(--success); }

    .tool-description { color: var(--gray-600); font-size: 0.875rem; margin-bottom: 1rem; }

    .tool-stats { display: flex; gap: 1rem; margin-bottom: 1rem; flex-wrap: wrap; }
    .tool-stat { font-size: 0.75rem; color: var(--gray-600); }

    .expand-btn {
      background: var(--primary);
      color: white;
      border: none;
      padding: 0.5rem 1rem;
      border-radius: 0.375rem;
      cursor: pointer;
      font-size: 0.875rem;
    }

    .expand-btn:hover { background: var(--primary-dark); }

    .tool-details {
      margin-top: 1rem;
      padding-top: 1rem;
      border-top: 1px solid var(--gray-200);
    }

    .tool-details h4 { font-size: 0.875rem; color: var(--gray-600); margin: 1rem 0 0.5rem; }
    .tool-details pre { background: var(--gray-800); color: #e5e7eb; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; font-size: 0.75rem; }
    .tool-details ul { list-style: disc; margin-left: 1.5rem; }
    .tool-details li { margin-bottom: 0.25rem; font-size: 0.875rem; }
    .warning-list li { color: var(--warning); }
    .security-list li { color: var(--danger); }

    .workflows-grid { display: flex; flex-direction: column; gap: 1.5rem; }

    .workflow-card {
      background: var(--gray-50);
      border: 1px solid var(--gray-200);
      border-radius: 0.75rem;
      padding: 1.5rem;
    }

    .workflow-card.success { border-left: 4px solid var(--success); }
    .workflow-card.failure { border-left: 4px solid var(--danger); }

    .workflow-header h3 { font-size: 1.25rem; margin-bottom: 0.5rem; }
    .workflow-description { color: var(--gray-600); margin-bottom: 1rem; }
    .workflow-summary { font-style: italic; border-left: 3px solid var(--primary); padding-left: 1rem; margin-bottom: 1rem; }

    .workflow-diagram { background: white; padding: 1rem; border-radius: 0.5rem; margin-bottom: 1rem; overflow-x: auto; }

    .workflow-steps h4 { margin-bottom: 0.5rem; }

    .workflow-step {
      display: flex;
      align-items: center;
      gap: 1rem;
      padding: 0.75rem;
      margin-bottom: 0.5rem;
      background: white;
      border-radius: 0.375rem;
      flex-wrap: wrap;
    }

    .workflow-step.step-success { border-left: 3px solid var(--success); }
    .workflow-step.step-failure { border-left: 3px solid var(--danger); }

    .step-number { font-weight: bold; color: var(--gray-600); }
    .step-tool { font-weight: 600; }
    .step-status { margin-left: auto; }
    .step-analysis { width: 100%; font-size: 0.875rem; color: var(--gray-600); margin-top: 0.5rem; }
    .step-error { width: 100%; font-size: 0.875rem; color: var(--danger); margin-top: 0.5rem; }

    .filter-bar { margin-bottom: 1rem; display: flex; gap: 1rem; flex-wrap: wrap; }
    .filter-bar label { display: flex; align-items: center; gap: 0.25rem; cursor: pointer; }

    .findings-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.875rem;
    }

    .findings-table th, .findings-table td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid var(--gray-200);
    }

    .findings-table th {
      background: var(--gray-50);
      font-weight: 600;
      cursor: pointer;
    }

    .findings-table th:hover { background: var(--gray-100); }

    .badge {
      padding: 0.25rem 0.5rem;
      border-radius: 9999px;
      font-size: 0.75rem;
      font-weight: 500;
    }

    .badge-behavior { background: #dbeafe; color: #1e40af; }
    .badge-limitation { background: #fef3c7; color: #92400e; }
    .badge-security { background: #fee2e2; color: #991b1b; }

    .security-group { padding: 1rem; border-radius: 0.5rem; margin-bottom: 1rem; }
    .security-group.critical { background: #fee2e2; }
    .security-group.warning { background: #fef3c7; }
    .security-group.info { background: #dbeafe; }
    .security-group h3 { margin-bottom: 0.5rem; }
    .security-group ul { list-style: disc; margin-left: 1.5rem; }
    .security-group li { margin-bottom: 0.25rem; }

    .no-findings { color: var(--success); font-style: italic; }

    .limitations-list, .recommendations-list { list-style: disc; margin-left: 1.5rem; }
    .limitations-list li, .recommendations-list li { margin-bottom: 0.5rem; }

    .footer {
      text-align: center;
      padding: 2rem;
      color: var(--gray-600);
      font-size: 0.875rem;
    }

    .footer a { color: var(--primary); }

    @media (max-width: 640px) {
      .container { padding: 1rem; }
      .header h1 { font-size: 1.75rem; }
      .tools-grid { grid-template-columns: 1fr; }
    }
  `;
}

/**
 * Get JavaScript for interactive features.
 */
function getScripts(): string {
  return `
    function filterTools() {
      const search = document.getElementById('tool-search').value.toLowerCase();
      const cards = document.querySelectorAll('.tool-card');

      cards.forEach(card => {
        const name = card.getAttribute('data-tool').toLowerCase();
        const description = card.querySelector('.tool-description').textContent.toLowerCase();
        card.style.display = (name.includes(search) || description.includes(search)) ? '' : 'none';
      });
    }

    function toggleToolDetails(toolName) {
      const details = document.getElementById('details-' + toolName);
      const btn = details.previousElementSibling;

      if (details.style.display === 'none') {
        details.style.display = 'block';
        btn.textContent = 'Hide Details';
      } else {
        details.style.display = 'none';
        btn.textContent = 'Show Details';
      }
    }

    function filterFindings() {
      const showBehavior = document.getElementById('filter-behavior').checked;
      const showLimitations = document.getElementById('filter-limitations').checked;
      const showSecurity = document.getElementById('filter-security').checked;

      document.querySelectorAll('.findings-table tbody tr').forEach(row => {
        const classes = row.className;
        let show = false;

        if (classes.includes('finding-behavior') && showBehavior) show = true;
        if (classes.includes('finding-limitations') && showLimitations) show = true;
        if (classes.includes('finding-security') && showSecurity) show = true;

        row.style.display = show ? '' : 'none';
      });
    }

    function sortTable(columnIndex) {
      const table = document.getElementById('findings-table');
      const tbody = table.querySelector('tbody');
      const rows = Array.from(tbody.querySelectorAll('tr'));

      const sorted = rows.sort((a, b) => {
        const aText = a.cells[columnIndex].textContent;
        const bText = b.cells[columnIndex].textContent;
        return aText.localeCompare(bText);
      });

      // Check if already sorted ascending
      const isAscending = tbody.getAttribute('data-sort') === columnIndex + '-asc';
      if (isAscending) {
        sorted.reverse();
        tbody.setAttribute('data-sort', columnIndex + '-desc');
      } else {
        tbody.setAttribute('data-sort', columnIndex + '-asc');
      }

      sorted.forEach(row => tbody.appendChild(row));
    }

    // Initialize mermaid if available
    if (typeof mermaid !== 'undefined') {
      mermaid.initialize({ startOnLoad: true, theme: 'neutral' });
    }
  `;
}

/**
 * Escape HTML special characters.
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Format date for display.
 */
function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

/**
 * Format duration for display.
 */
function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  return `${minutes}m ${seconds}s`;
}
