/**
 * Documentation templates for AGENTS.md generation.
 */

export const AGENTS_MD_HEADER = `# {{serverName}}

> Generated by [Inquest](https://github.com/dotsetlabs/inquest) on {{date}}

`;

export const OVERVIEW_SECTION = `## Overview

{{summary}}

**Server Version:** {{version}}
**Protocol Version:** {{protocolVersion}}

`;

export const CAPABILITIES_SECTION = `## Capabilities

{{#each capabilities}}
- **{{name}}**: {{count}} available
{{/each}}

`;

export const TOOL_SECTION_HEADER = `## Tools

`;

export const TOOL_ENTRY = `### {{name}}

{{description}}

**Input Schema:**
\`\`\`json
{{inputSchema}}
\`\`\`

{{#if behavioralNotes}}
**Observed Behavior:**
{{#each behavioralNotes}}
- {{this}}
{{/each}}
{{/if}}

{{#if limitations}}
**Limitations:**
{{#each limitations}}
- {{this}}
{{/each}}
{{/if}}

{{#if securityNotes}}
**Security Considerations:**
{{#each securityNotes}}
- {{this}}
{{/each}}
{{/if}}

`;

export const LIMITATIONS_SECTION = `## Known Limitations

{{#each limitations}}
- {{this}}
{{/each}}

`;

export const RECOMMENDATIONS_SECTION = `## Recommendations

{{#each recommendations}}
- {{this}}
{{/each}}

`;

export const INTERVIEW_METADATA = `---

*Interview completed in {{duration}}ms with {{toolCalls}} tool calls.*
`;
