/**
 * Tests for configuration template generation.
 */

import { describe, it, expect } from 'vitest';
import {
  generateConfigTemplate,
  generatePresetConfig,
  getPresetOverrides,
  PRESETS,
  type ConfigTemplateOptions,
} from '../../src/config/template.js';

describe('generateConfigTemplate', () => {
  describe('basic template generation', () => {
    it('should generate a valid YAML template', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('server:');
      expect(template).toContain('llm:');
      expect(template).toContain('explore:');
      expect(template).toContain('output:');
      expect(template).toContain('baseline:');
    });

    it('should include helpful comments', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('# Bellwether Configuration');
      expect(template).toContain('# Generated by');
      expect(template).toContain('bellwether check');
      expect(template).toContain('bellwether explore');
    });

    it('should include documentation link', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('https://docs.bellwether.sh');
    });
  });

  describe('server command options', () => {
    it('should include provided server command', () => {
      const template = generateConfigTemplate({
        serverCommand: 'npx @company/mcp-server',
      });

      expect(template).toContain('command: "npx @company/mcp-server"');
    });

    it('should default to empty command', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('command: ""');
    });

    it('should include server arguments', () => {
      const template = generateConfigTemplate({
        serverArgs: ['--port', '3000', '--config', 'prod.json'],
      });

      expect(template).toContain('args:');
      expect(template).toContain('"--port"');
      expect(template).toContain('"3000"');
      expect(template).toContain('"--config"');
    });

    it('should use empty args array when no args provided', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('args: []');
    });
  });

  describe('LLM provider options', () => {
    it('should include provided provider', () => {
      const template = generateConfigTemplate({
        provider: 'anthropic',
      });

      expect(template).toContain('provider: anthropic');
    });

    it('should default to ollama provider', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('provider: ollama');
    });

    it('should include openai provider when specified', () => {
      const template = generateConfigTemplate({
        provider: 'openai',
      });

      expect(template).toContain('provider: openai');
    });

    it('should include Ollama settings', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('ollama:');
      expect(template).toContain('baseUrl:');
      expect(template).toContain('http://localhost:11434');
    });
  });

  describe('preset options', () => {
    it('should include preset comment when preset is provided', () => {
      const template = generateConfigTemplate({
        preset: 'ci',
      });

      expect(template).toContain('# Generated with: bellwether init --preset ci');
    });

    it('should not include preset comment when not provided', () => {
      const template = generateConfigTemplate();

      expect(template).not.toContain('--preset');
    });
  });

  describe('CI optimization', () => {
    it('should set failOnDrift to true when ciOptimized', () => {
      const template = generateConfigTemplate({
        ciOptimized: true,
      });

      expect(template).toContain('failOnDrift: true');
    });

    it('should set failOnDrift to false when not ciOptimized', () => {
      const template = generateConfigTemplate({
        ciOptimized: false,
      });

      expect(template).toContain('failOnDrift: false');
    });
  });

  describe('environment variables', () => {
    it('should include detected env vars', () => {
      const template = generateConfigTemplate({
        envVars: ['API_KEY', 'DATABASE_URL'],
      });

      expect(template).toContain('env:');
      expect(template).toContain('API_KEY');
      expect(template).toContain('DATABASE_URL');
      expect(template).toContain('${API_KEY}');
      expect(template).toContain('${DATABASE_URL}');
    });

    it('should show example env vars when none provided', () => {
      const template = generateConfigTemplate({
        envVars: [],
      });

      expect(template).toContain('# env:');
      expect(template).toContain('#   NODE_ENV:');
    });
  });

  describe('sections completeness', () => {
    it('should include SERVER section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('# SERVER');
      expect(template).toContain('timeout:');
    });

    it('should include SCENARIOS section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('scenarios:');
      expect(template).toContain('only: false');
    });

    it('should include OUTPUT section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('output:');
      expect(template).toContain('dir:');
      expect(template).toContain('docsDir:');
    });

    it('should include CHECK COMMAND SETTINGS section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('# CHECK COMMAND SETTINGS');
      expect(template).toContain('baseline:');
      expect(template).toContain('failOnDrift:');
      expect(template).toContain('statefulTesting:');
      expect(template).toContain('externalServices:');
      expect(template).toContain('assertions:');
      expect(template).toContain('rateLimit:');
      expect(template).toContain('metrics:');
    });

    it('should include EXPLORE COMMAND SETTINGS section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('# EXPLORE COMMAND SETTINGS');
      expect(template).toContain('explore:');
      expect(template).toContain('personas:');
      expect(template).toContain('maxQuestionsPerTool:');
    });

    it('should include WORKFLOWS section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('workflows:');
      expect(template).toContain('discover:');
      expect(template).toContain('trackState:');
    });

    it('should include COMMON SETTINGS section', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('# COMMON SETTINGS');
      expect(template).toContain('cache:');
      expect(template).toContain('logging:');
    });
  });

  describe('persona options', () => {
    it('should include all persona options in comments', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('technical_writer');
      expect(template).toContain('security_tester');
      expect(template).toContain('qa_engineer');
      expect(template).toContain('novice_user');
    });

    it('should include persona descriptions', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('Documentation quality');
      expect(template).toContain('Security vulnerabilities');
      expect(template).toContain('Edge cases');
      expect(template).toContain('Usability');
    });
  });

  describe('security warnings', () => {
    it('should warn about not putting API keys in config', () => {
      const template = generateConfigTemplate();

      expect(template).toContain('SECURITY');
      expect(template).toContain('Never put API keys directly');
    });
  });
});

describe('PRESETS', () => {
  it('should have ci preset', () => {
    expect(PRESETS.ci).toBeDefined();
    expect(PRESETS.ci.ciOptimized).toBe(true);
  });

  it('should have security preset', () => {
    expect(PRESETS.security).toBeDefined();
    expect(PRESETS.security.provider).toBe('anthropic');
  });

  it('should have thorough preset', () => {
    expect(PRESETS.thorough).toBeDefined();
    expect(PRESETS.thorough.provider).toBe('anthropic');
  });

  it('should have local preset', () => {
    expect(PRESETS.local).toBeDefined();
    expect(PRESETS.local.provider).toBe('ollama');
  });

  it('should have all expected presets', () => {
    expect(Object.keys(PRESETS)).toContain('ci');
    expect(Object.keys(PRESETS)).toContain('security');
    expect(Object.keys(PRESETS)).toContain('thorough');
    expect(Object.keys(PRESETS)).toContain('local');
  });
});

describe('getPresetOverrides', () => {
  describe('ci preset', () => {
    it('should return CI-specific overrides', () => {
      const overrides = getPresetOverrides('ci');

      expect(overrides).not.toBeNull();
      expect(overrides).toContain('CI Preset Overrides');
      expect(overrides).toContain('failOnDrift: true');
      expect(overrides).toContain('level: warn');
    });
  });

  describe('security preset', () => {
    it('should return security-specific overrides', () => {
      const overrides = getPresetOverrides('security');

      expect(overrides).not.toBeNull();
      expect(overrides).toContain('Security Preset Overrides');
      expect(overrides).toContain('provider: anthropic');
      expect(overrides).toContain('security_tester');
      expect(overrides).toContain('maxQuestionsPerTool: 5');
    });
  });

  describe('thorough preset', () => {
    it('should return thorough-specific overrides', () => {
      const overrides = getPresetOverrides('thorough');

      expect(overrides).not.toBeNull();
      expect(overrides).toContain('Thorough Preset Overrides');
      expect(overrides).toContain('technical_writer');
      expect(overrides).toContain('security_tester');
      expect(overrides).toContain('qa_engineer');
      expect(overrides).toContain('novice_user');
      expect(overrides).toContain('parallelPersonas: true');
      expect(overrides).toContain('discover: true');
    });
  });

  describe('local preset', () => {
    it('should return local-specific overrides', () => {
      const overrides = getPresetOverrides('local');

      expect(overrides).not.toBeNull();
      expect(overrides).toContain('Local Preset Overrides');
      expect(overrides).toContain('provider: ollama');
      expect(overrides).toContain('http://localhost:11434');
    });
  });

  describe('unknown preset', () => {
    it('should return null for unknown preset', () => {
      const overrides = getPresetOverrides('nonexistent');

      expect(overrides).toBeNull();
    });
  });
});

describe('generatePresetConfig', () => {
  describe('ci preset', () => {
    it('should generate CI-optimized config', () => {
      const config = generatePresetConfig('ci');

      expect(config).toContain('failOnDrift: true');
      expect(config).toContain('--preset ci');
    });

    it('should merge with additional options', () => {
      const config = generatePresetConfig('ci', {
        serverCommand: 'npx my-server',
      });

      expect(config).toContain('command: "npx my-server"');
      expect(config).toContain('failOnDrift: true');
    });
  });

  describe('security preset', () => {
    it('should generate security-focused config', () => {
      const config = generatePresetConfig('security');

      expect(config).toContain('provider: anthropic');
      expect(config).toContain('--preset security');
    });
  });

  describe('thorough preset', () => {
    it('should generate thorough exploration config', () => {
      const config = generatePresetConfig('thorough');

      expect(config).toContain('provider: anthropic');
      expect(config).toContain('--preset thorough');
    });
  });

  describe('local preset', () => {
    it('should generate local Ollama config', () => {
      const config = generatePresetConfig('local');

      expect(config).toContain('provider: ollama');
      expect(config).toContain('--preset local');
    });
  });

  describe('unknown preset', () => {
    it('should throw for unknown preset', () => {
      expect(() => generatePresetConfig('nonexistent')).toThrow('Unknown preset: nonexistent');
    });

    it('should include available presets in error message', () => {
      try {
        generatePresetConfig('invalid');
        expect.fail('Should have thrown');
      } catch (error) {
        expect((error as Error).message).toContain('ci');
        expect((error as Error).message).toContain('security');
        expect((error as Error).message).toContain('thorough');
        expect((error as Error).message).toContain('local');
      }
    });
  });

  describe('option merging', () => {
    it('should allow overriding preset defaults', () => {
      const config = generatePresetConfig('local', {
        provider: 'openai', // Override the local preset's ollama
      });

      // The override should take effect
      expect(config).toContain('provider: openai');
    });

    it('should preserve preset name in comment', () => {
      const config = generatePresetConfig('ci', {
        serverCommand: 'custom-server',
      });

      expect(config).toContain('--preset ci');
    });
  });
});

describe('template validity', () => {
  it('should generate parseable YAML for default config', () => {
    const template = generateConfigTemplate();

    // Basic YAML structure checks
    expect(template).not.toContain('undefined');
    expect(template).not.toContain('[object Object]');

    // Check for balanced quotes
    const doubleQuotes = (template.match(/"/g) || []).length;
    expect(doubleQuotes % 2).toBe(0);
  });

  it('should generate parseable YAML for all presets', () => {
    for (const preset of Object.keys(PRESETS)) {
      const config = generatePresetConfig(preset);

      expect(config).not.toContain('undefined');
      expect(config).not.toContain('[object Object]');
    }
  });

  it('should handle special characters in server command', () => {
    const template = generateConfigTemplate({
      serverCommand: 'npx @scope/package --flag="value with spaces"',
    });

    expect(template).toContain('@scope/package');
  });

  it('should handle special characters in env vars', () => {
    const template = generateConfigTemplate({
      envVars: ['MY_SPECIAL_VAR', 'ANOTHER_VAR_123'],
    });

    expect(template).toContain('MY_SPECIAL_VAR');
    expect(template).toContain('ANOTHER_VAR_123');
  });
});

describe('template sections order', () => {
  it('should have SERVER section before LLM section', () => {
    const template = generateConfigTemplate();
    const serverIndex = template.indexOf('# SERVER');
    const llmIndex = template.indexOf('provider:');

    expect(serverIndex).toBeLessThan(llmIndex);
  });

  it('should have CHECK section before EXPLORE section', () => {
    const template = generateConfigTemplate();
    const checkIndex = template.indexOf('# CHECK COMMAND SETTINGS');
    const exploreIndex = template.indexOf('# EXPLORE COMMAND SETTINGS');

    expect(checkIndex).toBeLessThan(exploreIndex);
  });

  it('should have COMMON SETTINGS at the end', () => {
    const template = generateConfigTemplate();
    const commonIndex = template.indexOf('# COMMON SETTINGS');
    const loggingIndex = template.indexOf('logging:');

    expect(commonIndex).toBeLessThan(loggingIndex);
  });
});
