name: 'Bellwether MCP Test'
description: 'Behavioral testing and drift detection for MCP servers'
author: 'Dotset Labs LLC'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  server-command:
    description: 'MCP server command to test (e.g., "npx @mcp/your-server")'
    required: true
  server-args:
    description: 'Arguments to pass to the server command'
    required: false
    default: ''
  config-path:
    description: 'Path to bellwether.yaml config file. If not found, creates one with --preset ci'
    required: false
    default: 'bellwether.yaml'
  baseline-path:
    description: 'Path to baseline file for drift comparison'
    required: false
    default: 'bellwether-baseline.json'
  fail-on-drift:
    description: 'Fail the action if behavioral drift is detected'
    default: 'true'
  save-baseline:
    description: 'Save baseline after test'
    default: 'false'
  output-dir:
    description: 'Directory for output files'
    default: '.'

outputs:
  result:
    description: 'Check result: passed or failed'
    value: ${{ steps.test.outputs.result }}
  exit-code:
    description: 'Exit code (0=pass, 1=drift/fail, 2=error)'
    value: ${{ steps.test.outputs.exit-code }}
  drift-detected:
    description: 'Whether behavioral drift was detected (true/false)'
    value: ${{ steps.test.outputs.drift-detected }}
  tool-count:
    description: 'Number of tools discovered'
    value: ${{ steps.test.outputs.tool-count }}
  agents-md:
    description: 'Path to generated AGENTS.md file'
    value: ${{ steps.test.outputs.agents-md }}
  baseline-file:
    description: 'Path to baseline file'
    value: ${{ steps.test.outputs.baseline-file }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Bellwether
      shell: bash
      run: npm install -g @dotsetlabs/bellwether

    - name: Initialize Config (if needed)
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "::notice::Config not found, creating with --preset ci"
          bellwether init --preset ci ${{ inputs.server-command }} ${{ inputs.server-args }}
        fi

    - name: Run Bellwether Test
      shell: bash
      id: test
      env:
        BELLWETHER_CI: 'true'
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ env.ANTHROPIC_API_KEY }}
        OLLAMA_BASE_URL: ${{ env.OLLAMA_BASE_URL }}
        BELLWETHER_SESSION: ${{ env.BELLWETHER_SESSION }}
        BELLWETHER_API_URL: ${{ env.BELLWETHER_API_URL }}
      run: |
        set +e

        CONFIG_PATH="${{ inputs.config-path }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        BASELINE_PATH="${{ inputs.baseline-path }}"

        # Run test
        echo "Running: bellwether test --config $CONFIG_PATH ${{ inputs.server-command }} ${{ inputs.server-args }}"
        TEST_OUTPUT=$(bellwether test --config "$CONFIG_PATH" ${{ inputs.server-command }} ${{ inputs.server-args }} 2>&1)
        TEST_EXIT=$?

        echo "$TEST_OUTPUT"

        # Extract tool count from output
        TOOL_COUNT=$(echo "$TEST_OUTPUT" | grep -oP 'Discovered \K\d+(?= tools)' || echo "0")
        echo "tool-count=$TOOL_COUNT" >> $GITHUB_OUTPUT

        # Check for AGENTS.md
        AGENTS_MD="${OUTPUT_DIR}/AGENTS.md"
        if [ -f "$AGENTS_MD" ]; then
          echo "agents-md=$AGENTS_MD" >> $GITHUB_OUTPUT
        fi

        # If test failed, exit early
        if [ $TEST_EXIT -ne 0 ]; then
          echo "exit-code=$TEST_EXIT" >> $GITHUB_OUTPUT
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "drift-detected=false" >> $GITHUB_OUTPUT
          echo "::error::Bellwether test failed with exit code $TEST_EXIT"
          exit $TEST_EXIT
        fi

        # Save baseline if requested
        if [ "${{ inputs.save-baseline }}" = "true" ]; then
          echo "Saving baseline..."
          bellwether baseline save "$BASELINE_PATH" --force
          echo "baseline-file=$BASELINE_PATH" >> $GITHUB_OUTPUT
        fi

        # Compare baseline if it exists
        DRIFT_EXIT=0
        if [ -f "$BASELINE_PATH" ] && [ "${{ inputs.save-baseline }}" != "true" ]; then
          echo "Comparing against baseline: $BASELINE_PATH"

          COMPARE_FLAGS=""
          if [ "${{ inputs.fail-on-drift }}" = "true" ]; then
            COMPARE_FLAGS="--fail-on-drift"
          fi

          COMPARE_OUTPUT=$(bellwether baseline compare "$BASELINE_PATH" $COMPARE_FLAGS 2>&1)
          DRIFT_EXIT=$?

          echo "$COMPARE_OUTPUT"

          if [ $DRIFT_EXIT -ne 0 ]; then
            echo "drift-detected=true" >> $GITHUB_OUTPUT
            echo "::warning::Behavioral drift detected"
          else
            echo "drift-detected=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "drift-detected=false" >> $GITHUB_OUTPUT
          echo "baseline-file=$BASELINE_PATH" >> $GITHUB_OUTPUT
        fi

        # Set final result
        FINAL_EXIT=$DRIFT_EXIT
        echo "exit-code=$FINAL_EXIT" >> $GITHUB_OUTPUT

        if [ $FINAL_EXIT -eq 0 ]; then
          echo "result=passed" >> $GITHUB_OUTPUT
          echo "::notice::Bellwether test passed"
        else
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "::error::Bellwether check failed. Review the output above for details."
          echo ""
          echo "If drift was detected and changes are intentional, update your baseline:"
          echo "  bellwether test ${{ inputs.server-command }}"
          echo "  bellwether baseline save"
        fi

        exit $FINAL_EXIT

    - name: Upload AGENTS.md artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-docs
        path: ${{ inputs.output-dir }}/AGENTS.md
        if-no-files-found: ignore

    - name: Upload baseline artifact
      if: inputs.save-baseline == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-baseline
        path: ${{ inputs.baseline-path }}
        if-no-files-found: ignore

    - name: Upload JSON report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-report
        path: ${{ inputs.output-dir }}/bellwether-report.json
        if-no-files-found: ignore
