name: 'Bellwether MCP Check'
description: 'Schema validation and drift detection for MCP servers'
author: 'Dotset Labs LLC'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  server-command:
    description: 'MCP server command to check (e.g., "npx @mcp/your-server")'
    required: true
  server-args:
    description: 'Arguments to pass to the server command'
    required: false
    default: ''
  config-path:
    description: 'Path to bellwether.yaml config file (required for all commands). If not found, creates one with --preset ci'
    required: false
    default: 'bellwether.yaml'
  baseline-path:
    description: 'Path to baseline file for drift comparison (relative to output.dir unless absolute)'
    required: false
    default: 'bellwether-baseline.json'
  fail-on-drift:
    description: 'Fail the action if schema drift is detected (deprecated: use fail-on-severity instead)'
    default: 'true'
  save-baseline:
    description: 'Save baseline after check'
    default: 'false'
  output-dir:
    description: 'Directory for output files (must match bellwether.yaml output.dir/docsDir for artifacts)'
    default: '.'
  format:
    description: 'Output format: text, json, compact, github, markdown, junit, sarif'
    required: false
    default: 'github'
  parallel:
    description: 'Enable parallel tool testing for faster checks'
    required: false
    default: 'true'
  parallel-workers:
    description: 'Number of concurrent tool workers (1-10)'
    required: false
    default: '4'
  incremental:
    description: 'Only test tools with changed schemas (requires existing baseline)'
    required: false
    default: 'false'
  incremental-cache-hours:
    description: 'Max age of cached results in hours for incremental mode'
    required: false
    default: '168'
  performance-threshold:
    description: 'Performance regression threshold percentage (0-100)'
    required: false
    default: '10'
  min-severity:
    description: 'Minimum severity to report: none, info, warning, breaking'
    required: false
    default: 'info'
  fail-on-severity:
    description: 'Fail threshold severity: none, info, warning, breaking'
    required: false
    default: 'breaking'
  accept-drift:
    description: 'Accept detected drift as intentional and update baseline'
    required: false
    default: 'false'
  accept-reason:
    description: 'Reason for accepting drift (used with accept-drift: true)'
    required: false
    default: ''
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'
  security:
    description: 'Enable security testing (injection, traversal, etc.)'
    required: false
    default: 'false'

outputs:
  result:
    description: 'Check result: passed or failed'
    value: ${{ steps.test.outputs.result }}
  exit-code:
    description: 'Semantic exit code: 0=clean, 1=info, 2=warning, 3=breaking, 4=error'
    value: ${{ steps.test.outputs.exit-code }}
  severity:
    description: 'Highest change severity detected: none, info, warning, breaking'
    value: ${{ steps.test.outputs.severity }}
  drift-detected:
    description: 'Whether schema drift was detected (true/false)'
    value: ${{ steps.test.outputs.drift-detected }}
  tool-count:
    description: 'Number of tools discovered'
    value: ${{ steps.test.outputs.tool-count }}
  contract-md:
    description: 'Path to generated CONTRACT.md file'
    value: ${{ steps.test.outputs.contract-md }}
  baseline-file:
    description: 'Path to baseline file'
    value: ${{ steps.test.outputs.baseline-file }}
  sarif-file:
    description: 'Path to SARIF file (when format includes sarif)'
    value: ${{ steps.test.outputs.sarif-file }}
  junit-file:
    description: 'Path to JUnit XML file (when format includes junit)'
    value: ${{ steps.test.outputs.junit-file }}
  doc-score:
    description: 'Documentation quality score (0-100)'
    value: ${{ steps.test.outputs.doc-score }}
  doc-grade:
    description: 'Documentation quality grade (A-F)'
    value: ${{ steps.test.outputs.doc-grade }}
  security-findings:
    description: 'Number of security findings (when --security enabled)'
    value: ${{ steps.test.outputs.security-findings }}
  breaking-count:
    description: 'Number of breaking changes detected'
    value: ${{ steps.test.outputs.breaking-count }}
  warning-count:
    description: 'Number of warning-level changes detected'
    value: ${{ steps.test.outputs.warning-count }}
  info-count:
    description: 'Number of info-level changes detected'
    value: ${{ steps.test.outputs.info-count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Bellwether
      shell: bash
      run: npm install -g @dotsetlabs/bellwether

    - name: Initialize Config (if needed)
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "::notice::Config not found, creating with --preset ci"
          bellwether init --preset ci ${{ inputs.server-command }} ${{ inputs.server-args }}
        fi

    - name: Run Bellwether Check
      shell: bash
      id: test
      env:
        BELLWETHER_CI: 'true'
        BELLWETHER_SESSION: ${{ env.BELLWETHER_SESSION }}
        BELLWETHER_API_URL: ${{ env.BELLWETHER_API_URL }}
      run: |
        set +e

        CONFIG_PATH="${{ inputs.config-path }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        BASELINE_PATH="${{ inputs.baseline-path }}"
        SAVE_BASELINE="${{ inputs.save-baseline }}"

        # Build check command flags
        CHECK_FLAGS="--config $CONFIG_PATH"
        CHECK_FLAGS="$CHECK_FLAGS --format ${{ inputs.format }}"

        # Parallel options
        if [ "${{ inputs.parallel }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --parallel --parallel-workers ${{ inputs.parallel-workers }}"
        fi

        # Incremental options
        if [ "${{ inputs.incremental }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --incremental --incremental-cache-hours ${{ inputs.incremental-cache-hours }}"
        fi

        # Performance threshold
        CHECK_FLAGS="$CHECK_FLAGS --performance-threshold ${{ inputs.performance-threshold }}"

        # Severity options
        CHECK_FLAGS="$CHECK_FLAGS --min-severity ${{ inputs.min-severity }}"
        CHECK_FLAGS="$CHECK_FLAGS --fail-on-severity ${{ inputs.fail-on-severity }}"

        # Accept drift options
        if [ "${{ inputs.accept-drift }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --accept-drift"
          if [ -n "${{ inputs.accept-reason }}" ]; then
            CHECK_FLAGS="$CHECK_FLAGS --accept-reason \"${{ inputs.accept-reason }}\""
          fi
        fi

        # Legacy fail-on-drift support
        if [ "${{ inputs.fail-on-drift }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --fail-on-drift"
        fi

        # Security testing
        if [ "${{ inputs.security }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --security"
        fi

        # Run check
        echo "Running: bellwether check $CHECK_FLAGS ${{ inputs.server-command }} ${{ inputs.server-args }}"
        CHECK_OUTPUT=$(bellwether check $CHECK_FLAGS ${{ inputs.server-command }} ${{ inputs.server-args }} 2>&1)
        CHECK_EXIT=$?

        echo "$CHECK_OUTPUT"

        # Extract tool count from output (portable regex without Perl extensions)
        TOOL_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'Found [0-9]* tools' | grep -o '[0-9]*' | head -1 || echo "0")
        if [ -z "$TOOL_COUNT" ]; then
          TOOL_COUNT="0"
        fi
        echo "tool-count=$TOOL_COUNT" >> $GITHUB_OUTPUT

        # Check for CONTRACT.md in output dir or .bellwether default
        CONTRACT_MD="${OUTPUT_DIR}/CONTRACT.md"
        if [ ! -f "$CONTRACT_MD" ]; then
          CONTRACT_MD=".bellwether/CONTRACT.md"
        fi
        if [ -f "$CONTRACT_MD" ]; then
          echo "contract-md=$CONTRACT_MD" >> $GITHUB_OUTPUT
        fi

        # Set baseline file output
        echo "baseline-file=$BASELINE_PATH" >> $GITHUB_OUTPUT

        # Map exit code to severity (0.8.0 semantic exit codes)
        case $CHECK_EXIT in
          0) SEVERITY="none" ;;
          1) SEVERITY="info" ;;
          2) SEVERITY="warning" ;;
          3) SEVERITY="breaking" ;;
          4) SEVERITY="error" ;;
          *) SEVERITY="error" ;;
        esac
        echo "severity=$SEVERITY" >> $GITHUB_OUTPUT

        # Determine drift status from exit code
        if [ $CHECK_EXIT -ge 1 ] && [ $CHECK_EXIT -le 3 ]; then
          DRIFT_DETECTED="true"
        else
          DRIFT_DETECTED="false"
        fi
        echo "drift-detected=$DRIFT_DETECTED" >> $GITHUB_OUTPUT

        # Extract documentation quality from output
        DOC_SCORE=$(echo "$CHECK_OUTPUT" | grep -o 'doc_score=[0-9]*' | grep -o '[0-9]*' | head -1 || echo "")
        if [ -n "$DOC_SCORE" ]; then
          echo "doc-score=$DOC_SCORE" >> $GITHUB_OUTPUT
        fi
        DOC_GRADE=$(echo "$CHECK_OUTPUT" | grep -o 'doc_grade=[A-F]' | grep -o '[A-F]' | head -1 || echo "")
        if [ -n "$DOC_GRADE" ]; then
          echo "doc-grade=$DOC_GRADE" >> $GITHUB_OUTPUT
        fi

        # Extract security findings count
        SECURITY_FINDINGS=$(echo "$CHECK_OUTPUT" | grep -o 'new_security_findings=[0-9]*' | grep -o '[0-9]*' | head -1 || echo "0")
        echo "security-findings=$SECURITY_FINDINGS" >> $GITHUB_OUTPUT

        # Extract change counts from output
        BREAKING_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'Breaking changes: [0-9]*' | grep -o '[0-9]*' | head -1 || echo "0")
        echo "breaking-count=$BREAKING_COUNT" >> $GITHUB_OUTPUT
        WARNING_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'Warnings: [0-9]*' | grep -o '[0-9]*' | head -1 || echo "0")
        echo "warning-count=$WARNING_COUNT" >> $GITHUB_OUTPUT
        INFO_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'Info: [0-9]*' | grep -o '[0-9]*' | head -1 || echo "0")
        echo "info-count=$INFO_COUNT" >> $GITHUB_OUTPUT

        # Save baseline if requested and check was clean
        if [ $CHECK_EXIT -eq 0 ] && [ "$SAVE_BASELINE" = "true" ]; then
          echo ""
          echo "Saving baseline to $BASELINE_PATH..."
          bellwether baseline save "$BASELINE_PATH" --force
        fi

        # Generate SARIF file for GitHub Code Scanning
        SARIF_FILE="${OUTPUT_DIR}/bellwether.sarif"
        if [ "${{ inputs.upload-sarif }}" = "true" ]; then
          echo ""
          echo "Generating SARIF report..."
          bellwether check --config "$CONFIG_PATH" --format sarif ${{ inputs.server-command }} ${{ inputs.server-args }} > "$SARIF_FILE" 2>/dev/null || true
          if [ -f "$SARIF_FILE" ] && [ -s "$SARIF_FILE" ]; then
            echo "sarif-file=$SARIF_FILE" >> $GITHUB_OUTPUT
          fi
        fi

        # Generate JUnit file if requested
        if [ "${{ inputs.format }}" = "junit" ]; then
          JUNIT_FILE="${OUTPUT_DIR}/bellwether-junit.xml"
          echo ""
          echo "Generating JUnit report..."
          bellwether check --config "$CONFIG_PATH" --format junit ${{ inputs.server-command }} ${{ inputs.server-args }} > "$JUNIT_FILE" 2>/dev/null || true
          if [ -f "$JUNIT_FILE" ] && [ -s "$JUNIT_FILE" ]; then
            echo "junit-file=$JUNIT_FILE" >> $GITHUB_OUTPUT
          fi
        fi

        # Set final outputs
        echo "exit-code=$CHECK_EXIT" >> $GITHUB_OUTPUT

        if [ $CHECK_EXIT -eq 0 ]; then
          echo "result=passed" >> $GITHUB_OUTPUT
          echo "::notice::Bellwether check passed - no drift detected"
        elif [ $CHECK_EXIT -eq 1 ]; then
          echo "result=passed" >> $GITHUB_OUTPUT
          echo "::notice::Bellwether check passed - info-level changes detected (non-breaking)"
        elif [ $CHECK_EXIT -eq 2 ]; then
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "::warning::Bellwether check: warning-level changes detected"
        elif [ $CHECK_EXIT -eq 3 ]; then
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "::error::Bellwether check failed: breaking changes detected"
          echo ""
          echo "If changes are intentional, update your baseline:"
          echo "  bellwether baseline accept --reason \"Your reason here\" --force"
        else
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "::error::Bellwether check failed with error. Review the output above for details."
        fi

        exit $CHECK_EXIT

    - name: Upload CONTRACT.md artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-docs
        path: |
          ${{ inputs.output-dir }}/CONTRACT.md
          .bellwether/CONTRACT.md
        if-no-files-found: ignore

    - name: Upload baseline artifact
      if: inputs.save-baseline == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-baseline
        path: ${{ inputs.baseline-path }}
        if-no-files-found: ignore

    - name: Upload JSON report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-report
        path: |
          ${{ inputs.output-dir }}/bellwether-check.json
          .bellwether/bellwether-check.json
        if-no-files-found: ignore

    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.upload-sarif == 'true' && always() && steps.test.outputs.sarif-file != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.test.outputs.sarif-file }}
        category: bellwether-mcp-check
      continue-on-error: true

    - name: Upload JUnit artifact
      if: inputs.format == 'junit' && always() && steps.test.outputs.junit-file != ''
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-junit
        path: ${{ steps.test.outputs.junit-file }}
        if-no-files-found: ignore
