name: 'Bellwether MCP Check'
description: 'Schema validation and drift detection for MCP servers'
author: 'Dotset Labs LLC'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  server-command:
    description: 'MCP server command to check (e.g., "npx @mcp/your-server")'
    required: true
  server-args:
    description: 'Arguments to pass to the server command'
    required: false
    default: ''
  config-path:
    description: 'Path to bellwether.yaml config file. If not found, creates one with --preset ci'
    required: false
    default: 'bellwether.yaml'
  baseline-path:
    description: 'Path to baseline file for drift comparison'
    required: false
    default: 'bellwether-baseline.json'
  fail-on-drift:
    description: 'Fail the action if schema drift is detected'
    default: 'true'
  save-baseline:
    description: 'Save baseline after check'
    default: 'false'
  output-dir:
    description: 'Directory for output files'
    default: '.'

outputs:
  result:
    description: 'Check result: passed or failed'
    value: ${{ steps.test.outputs.result }}
  exit-code:
    description: 'Exit code (0=pass, 1=drift/fail, 2=error)'
    value: ${{ steps.test.outputs.exit-code }}
  drift-detected:
    description: 'Whether schema drift was detected (true/false)'
    value: ${{ steps.test.outputs.drift-detected }}
  tool-count:
    description: 'Number of tools discovered'
    value: ${{ steps.test.outputs.tool-count }}
  contract-md:
    description: 'Path to generated CONTRACT.md file'
    value: ${{ steps.test.outputs.contract-md }}
  baseline-file:
    description: 'Path to baseline file'
    value: ${{ steps.test.outputs.baseline-file }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Bellwether
      shell: bash
      run: npm install -g @dotsetlabs/bellwether

    - name: Initialize Config (if needed)
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        if [ ! -f "$CONFIG_PATH" ]; then
          echo "::notice::Config not found, creating with --preset ci"
          bellwether init --preset ci ${{ inputs.server-command }} ${{ inputs.server-args }}
        fi

    - name: Run Bellwether Check
      shell: bash
      id: test
      env:
        BELLWETHER_CI: 'true'
        BELLWETHER_SESSION: ${{ env.BELLWETHER_SESSION }}
        BELLWETHER_API_URL: ${{ env.BELLWETHER_API_URL }}
      run: |
        set +e

        CONFIG_PATH="${{ inputs.config-path }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        BASELINE_PATH="${{ inputs.baseline-path }}"

        # Build check command flags
        CHECK_FLAGS="--config $CONFIG_PATH"
        if [ -f "$BASELINE_PATH" ] && [ "${{ inputs.save-baseline }}" != "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --baseline $BASELINE_PATH"
        fi
        if [ "${{ inputs.fail-on-drift }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --fail-on-drift"
        fi
        if [ "${{ inputs.save-baseline }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --save-baseline $BASELINE_PATH"
        fi

        # Run check
        echo "Running: bellwether check $CHECK_FLAGS ${{ inputs.server-command }} ${{ inputs.server-args }}"
        CHECK_OUTPUT=$(bellwether check $CHECK_FLAGS ${{ inputs.server-command }} ${{ inputs.server-args }} 2>&1)
        CHECK_EXIT=$?

        echo "$CHECK_OUTPUT"

        # Extract tool count from output
        TOOL_COUNT=$(echo "$CHECK_OUTPUT" | grep -oP 'Found \K\d+(?= tools)' || echo "0")
        echo "tool-count=$TOOL_COUNT" >> $GITHUB_OUTPUT

        # Check for CONTRACT.md
        CONTRACT_MD="${OUTPUT_DIR}/CONTRACT.md"
        if [ -f "$CONTRACT_MD" ]; then
          echo "contract-md=$CONTRACT_MD" >> $GITHUB_OUTPUT
        fi

        # Set baseline file output
        echo "baseline-file=$BASELINE_PATH" >> $GITHUB_OUTPUT

        # Determine drift status from output
        if echo "$CHECK_OUTPUT" | grep -q "drift detected\|Breaking changes\|Warning-level changes"; then
          echo "drift-detected=true" >> $GITHUB_OUTPUT
        else
          echo "drift-detected=false" >> $GITHUB_OUTPUT
        fi

        # Set final result
        echo "exit-code=$CHECK_EXIT" >> $GITHUB_OUTPUT

        if [ $CHECK_EXIT -eq 0 ]; then
          echo "result=passed" >> $GITHUB_OUTPUT
          echo "::notice::Bellwether check passed"
        else
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "::error::Bellwether check failed. Review the output above for details."
          echo ""
          echo "If drift was detected and changes are intentional, update your baseline:"
          echo "  bellwether check ${{ inputs.server-command }} --save-baseline"
        fi

        exit $CHECK_EXIT

    - name: Upload CONTRACT.md artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-docs
        path: ${{ inputs.output-dir }}/CONTRACT.md
        if-no-files-found: ignore

    - name: Upload baseline artifact
      if: inputs.save-baseline == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-baseline
        path: ${{ inputs.baseline-path }}
        if-no-files-found: ignore

    - name: Upload JSON report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-report
        path: ${{ inputs.output-dir }}/bellwether-check.json
        if-no-files-found: ignore
