name: 'Bellwether MCP Check'
description: 'Schema validation and drift detection for MCP servers'
author: 'Dotset Labs LLC'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  server-command:
    description: 'MCP server command to check (e.g., "npx @mcp/your-server")'
    required: true
  server-args:
    description: 'Arguments to pass to the server command'
    required: false
    default: ''
  config-path:
    description: 'Path to bellwether.yaml config file (required for all commands). If not found, creates one with --preset ci'
    required: false
    default: 'bellwether.yaml'
  baseline-path:
    description: 'Path to baseline file for drift comparison (relative to output.dir unless absolute)'
    required: false
    default: 'bellwether-baseline.json'
  save-baseline:
    description: 'Save baseline after check'
    default: 'false'
  output-dir:
    description: 'Directory for output files (must match bellwether.yaml output.dir/docsDir for artifacts)'
    default: '.'
  format:
    description: 'Output format: text, json, compact, github, markdown, junit, sarif'
    required: false
    default: 'github'
  min-severity:
    description: 'Minimum severity to report: none, info, warning, breaking'
    required: false
    default: 'info'
  fail-on-severity:
    description: 'Fail threshold severity: none, info, warning, breaking'
    required: false
    default: 'breaking'
  accept-drift:
    description: 'Accept detected drift as intentional and update baseline'
    required: false
    default: 'false'
  accept-reason:
    description: 'Reason for accepting drift (used with accept-drift: true)'
    required: false
    default: ''
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'

outputs:
  result:
    description: 'Check result: passed or failed'
    value: ${{ steps.test.outputs.result }}
  exit-code:
    description: 'Semantic exit code: 0=clean, 1=info, 2=warning, 3=breaking, 4=error, 5=low-confidence'
    value: ${{ steps.test.outputs.exit-code }}
  severity:
    description: 'Highest change severity detected: none, info, warning, breaking, low_confidence'
    value: ${{ steps.test.outputs.severity }}
  drift-detected:
    description: 'Whether schema drift was detected (true/false)'
    value: ${{ steps.test.outputs.drift-detected }}
  tool-count:
    description: 'Number of tools discovered'
    value: ${{ steps.test.outputs.tool-count }}
  contract-md:
    description: 'Path to generated CONTRACT.md file'
    value: ${{ steps.test.outputs.contract-md }}
  baseline-file:
    description: 'Path to baseline file'
    value: ${{ steps.test.outputs.baseline-file }}
  sarif-file:
    description: 'Path to SARIF file (when format includes sarif)'
    value: ${{ steps.test.outputs.sarif-file }}
  junit-file:
    description: 'Path to JUnit XML file (when format includes junit)'
    value: ${{ steps.test.outputs.junit-file }}
  doc-score:
    description: 'Documentation quality score (0-100)'
    value: ${{ steps.test.outputs.doc-score }}
  doc-grade:
    description: 'Documentation quality grade (A-F)'
    value: ${{ steps.test.outputs.doc-grade }}
  security-findings:
    description: 'Number of security findings (when security testing is enabled)'
    value: ${{ steps.test.outputs.security-findings }}
  breaking-count:
    description: 'Number of breaking changes detected'
    value: ${{ steps.test.outputs.breaking-count }}
  warning-count:
    description: 'Number of warning-level changes detected'
    value: ${{ steps.test.outputs.warning-count }}
  info-count:
    description: 'Number of info-level changes detected'
    value: ${{ steps.test.outputs.info-count }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Bellwether
      shell: bash
      run: npm install -g @dotsetlabs/bellwether

    - name: Initialize Config (if needed)
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        DEFAULT_CONFIG="bellwether.yaml"
        if [ ! -f "$CONFIG_PATH" ]; then
          if [ "$CONFIG_PATH" != "$DEFAULT_CONFIG" ] && [ -f "$DEFAULT_CONFIG" ]; then
            mkdir -p "$(dirname "$CONFIG_PATH")"
            cp "$DEFAULT_CONFIG" "$CONFIG_PATH"
          else
            echo "::notice::Config not found, creating with --preset ci"
            bellwether init --preset ci ${{ inputs.server-command }} ${{ inputs.server-args }}
            if [ "$CONFIG_PATH" != "$DEFAULT_CONFIG" ]; then
              mkdir -p "$(dirname "$CONFIG_PATH")"
              mv "$DEFAULT_CONFIG" "$CONFIG_PATH"
            fi
          fi
        fi

    - name: Resolve Config Output Paths
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        CONFIG_META=$(node --input-type=module -e 'import fs from "fs"; import yaml from "yaml"; const path = process.argv[1]; const content = fs.readFileSync(path, "utf8"); const config = yaml.parse(content) || {}; const output = config.output || {}; const files = output.files || {}; const docsDir = output.docsDir || "."; const outputDir = output.dir || ".bellwether"; const contractFile = files.contractDoc || "CONTRACT.md"; const checkReport = files.checkReport || "bellwether-check.json"; console.log([docsDir, outputDir, contractFile, checkReport].join("|"));' "$CONFIG_PATH")
        IFS='|' read -r CONFIG_DOCS_DIR CONFIG_OUTPUT_DIR CONFIG_CONTRACT_FILE CONFIG_CHECK_REPORT <<< "$CONFIG_META"
        echo "BELLWETHER_CONFIG_DOCS_DIR=$CONFIG_DOCS_DIR" >> $GITHUB_ENV
        echo "BELLWETHER_CONFIG_OUTPUT_DIR=$CONFIG_OUTPUT_DIR" >> $GITHUB_ENV
        echo "BELLWETHER_CONFIG_CONTRACT_FILE=$CONFIG_CONTRACT_FILE" >> $GITHUB_ENV
        echo "BELLWETHER_CONFIG_CHECK_REPORT=$CONFIG_CHECK_REPORT" >> $GITHUB_ENV

    - name: Run Bellwether Check
      shell: bash
      id: test
      env:
        BELLWETHER_CI: 'true'
      run: |
        set +e

        CONFIG_PATH="${{ inputs.config-path }}"
        CONFIG_DOCS_DIR="${BELLWETHER_CONFIG_DOCS_DIR:-${{ inputs.output-dir }}}"
        CONFIG_OUTPUT_DIR="${BELLWETHER_CONFIG_OUTPUT_DIR:-${{ inputs.output-dir }}}"
        CONFIG_CONTRACT_FILE="${BELLWETHER_CONFIG_CONTRACT_FILE:-CONTRACT.md}"
        CONFIG_CHECK_REPORT="${BELLWETHER_CONFIG_CHECK_REPORT:-bellwether-check.json}"
        OUTPUT_DIR="${CONFIG_OUTPUT_DIR%/}"
        DOCS_DIR="${CONFIG_DOCS_DIR%/}"
        BASELINE_PATH_INPUT="${{ inputs.baseline-path }}"
        SAVE_BASELINE="${{ inputs.save-baseline }}"

        if [ -n "$OUTPUT_DIR" ] && [ ! -d "$OUTPUT_DIR" ]; then
          mkdir -p "$OUTPUT_DIR"
        fi

        if [ -n "$DOCS_DIR" ] && [ ! -d "$DOCS_DIR" ]; then
          mkdir -p "$DOCS_DIR"
        fi

        if [[ "$BASELINE_PATH_INPUT" = /* ]]; then
          BASELINE_PATH="$BASELINE_PATH_INPUT"
        else
          BASELINE_PATH="${OUTPUT_DIR}/${BASELINE_PATH_INPUT}"
        fi

        CONTRACT_MD="${DOCS_DIR}/${CONFIG_CONTRACT_FILE}"
        CHECK_REPORT_PATH="${OUTPUT_DIR}/${CONFIG_CHECK_REPORT}"

        echo "BELLWETHER_CONTRACT_PATH=$CONTRACT_MD" >> $GITHUB_ENV
        echo "BELLWETHER_CHECK_REPORT_PATH=$CHECK_REPORT_PATH" >> $GITHUB_ENV
        echo "BELLWETHER_BASELINE_PATH=$BASELINE_PATH" >> $GITHUB_ENV

        # Build check command flags
        CHECK_FLAGS="--config $CONFIG_PATH"

        # Severity options
        CHECK_FLAGS="$CHECK_FLAGS --min-severity ${{ inputs.min-severity }}"
        CHECK_FLAGS="$CHECK_FLAGS --fail-on-severity ${{ inputs.fail-on-severity }}"

        # Accept drift options
        if [ "${{ inputs.accept-drift }}" = "true" ]; then
          CHECK_FLAGS="$CHECK_FLAGS --accept-drift"
          if [ -n "${{ inputs.accept-reason }}" ]; then
            CHECK_FLAGS="$CHECK_FLAGS --accept-reason \"${{ inputs.accept-reason }}\""
          fi
        fi

        # Run check for parsing (compact output)
        echo "Running: bellwether check $CHECK_FLAGS --format compact ${{ inputs.server-command }} ${{ inputs.server-args }}"
        CHECK_OUTPUT=$(bellwether check $CHECK_FLAGS --format compact ${{ inputs.server-command }} ${{ inputs.server-args }} 2>&1)
        CHECK_EXIT=$?

        # Display output in requested format
        if [ "${{ inputs.format }}" = "compact" ]; then
          echo "$CHECK_OUTPUT"
        else
          bellwether check $CHECK_FLAGS --format ${{ inputs.format }} ${{ inputs.server-command }} ${{ inputs.server-args }} || true
        fi

        # Extract tool count from JSON report
        if [ -f "$CHECK_REPORT_PATH" ]; then
          TOOL_COUNT=$(node --input-type=module -e 'import fs from "fs"; const report = JSON.parse(fs.readFileSync(process.argv[1], "utf8")); console.log((report.toolProfiles || []).length);' "$CHECK_REPORT_PATH" 2>/dev/null || echo "0")
        else
          TOOL_COUNT="0"
        fi
        echo "tool-count=$TOOL_COUNT" >> $GITHUB_OUTPUT

        # Set CONTRACT.md output path
        if [ -f "$CONTRACT_MD" ]; then
          echo "contract-md=$CONTRACT_MD" >> $GITHUB_OUTPUT
        fi

        # Set baseline file output
        echo "baseline-file=$BASELINE_PATH" >> $GITHUB_OUTPUT

        # Map exit code to severity (0.8.0 semantic exit codes)
        case $CHECK_EXIT in
          0) SEVERITY="none" ;;
          1) SEVERITY="info" ;;
          2) SEVERITY="warning" ;;
          3) SEVERITY="breaking" ;;
          4) SEVERITY="error" ;;
          5) SEVERITY="low_confidence" ;;
          *) SEVERITY="error" ;;
        esac
        echo "severity=$SEVERITY" >> $GITHUB_OUTPUT

        # Determine drift status from exit code
        if [ $CHECK_EXIT -ge 1 ] && [ $CHECK_EXIT -le 3 ]; then
          DRIFT_DETECTED="true"
        else
          DRIFT_DETECTED="false"
        fi
        echo "drift-detected=$DRIFT_DETECTED" >> $GITHUB_OUTPUT

        # Extract documentation quality from compact output
        DOC_SCORE=$(echo "$CHECK_OUTPUT" | grep -o 'doc_score=[0-9]*' | grep -o '[0-9]*' | head -1 || echo "")
        if [ -n "$DOC_SCORE" ]; then
          echo "doc-score=$DOC_SCORE" >> $GITHUB_OUTPUT
        fi
        DOC_GRADE=$(echo "$CHECK_OUTPUT" | grep -o 'doc_grade=[A-F]' | grep -o '[A-F]' | head -1 || echo "")
        if [ -n "$DOC_GRADE" ]; then
          echo "doc-grade=$DOC_GRADE" >> $GITHUB_OUTPUT
        fi

        # Extract security findings count from compact output
        SECURITY_FINDINGS=$(echo "$CHECK_OUTPUT" | grep -o 'new_security_findings=[0-9]*' | grep -o '[0-9]*' | head -1 || echo "0")
        echo "security-findings=$SECURITY_FINDINGS" >> $GITHUB_OUTPUT

        # Extract change counts from compact output
        BREAKING_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'breaking=[0-9]*' | head -1 | cut -d= -f2 || echo "0")
        echo "breaking-count=$BREAKING_COUNT" >> $GITHUB_OUTPUT
        WARNING_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'warnings=[0-9]*' | head -1 | cut -d= -f2 || echo "0")
        echo "warning-count=$WARNING_COUNT" >> $GITHUB_OUTPUT
        INFO_COUNT=$(echo "$CHECK_OUTPUT" | grep -o 'info=[0-9]*' | head -1 | cut -d= -f2 || echo "0")
        echo "info-count=$INFO_COUNT" >> $GITHUB_OUTPUT

        # Save baseline if requested and check was clean
        if [ $CHECK_EXIT -eq 0 ] && [ "$SAVE_BASELINE" = "true" ]; then
          echo ""
          echo "Saving baseline to $BASELINE_PATH..."
          bellwether baseline save "$BASELINE_PATH" --force
        fi

        # Generate SARIF file for GitHub Code Scanning
        SARIF_FILE="${OUTPUT_DIR}/bellwether.sarif"
        if [ "${{ inputs.upload-sarif }}" = "true" ]; then
          echo ""
          echo "Generating SARIF report..."
          bellwether check --config "$CONFIG_PATH" --format sarif ${{ inputs.server-command }} ${{ inputs.server-args }} > "$SARIF_FILE" 2>/dev/null || true
          if [ -f "$SARIF_FILE" ] && [ -s "$SARIF_FILE" ]; then
            echo "sarif-file=$SARIF_FILE" >> $GITHUB_OUTPUT
          fi
        fi

        # Generate JUnit file if requested
        if [ "${{ inputs.format }}" = "junit" ]; then
          JUNIT_FILE="${OUTPUT_DIR}/bellwether-junit.xml"
          echo ""
          echo "Generating JUnit report..."
          bellwether check --config "$CONFIG_PATH" --format junit ${{ inputs.server-command }} ${{ inputs.server-args }} > "$JUNIT_FILE" 2>/dev/null || true
          if [ -f "$JUNIT_FILE" ] && [ -s "$JUNIT_FILE" ]; then
            echo "junit-file=$JUNIT_FILE" >> $GITHUB_OUTPUT
          fi
        fi

        # Set final outputs
        echo "exit-code=$CHECK_EXIT" >> $GITHUB_OUTPUT

        FAIL_THRESHOLD="${{ inputs.fail-on-severity }}"
        FAIL_THRESHOLD_LEVEL=3
        case "$FAIL_THRESHOLD" in
          none) FAIL_THRESHOLD_LEVEL=0 ;;
          info) FAIL_THRESHOLD_LEVEL=1 ;;
          warning) FAIL_THRESHOLD_LEVEL=2 ;;
          breaking) FAIL_THRESHOLD_LEVEL=3 ;;
        esac

        SHOULD_FAIL="false"
        if [ $CHECK_EXIT -eq 4 ] || [ $CHECK_EXIT -eq 5 ]; then
          SHOULD_FAIL="true"
        elif [ $CHECK_EXIT -ge 1 ] && [ $CHECK_EXIT -le 3 ]; then
          if [ $FAIL_THRESHOLD_LEVEL -gt 0 ] && [ $CHECK_EXIT -ge $FAIL_THRESHOLD_LEVEL ]; then
            SHOULD_FAIL="true"
          fi
        fi

        if [ "$SHOULD_FAIL" = "true" ]; then
          echo "result=failed" >> $GITHUB_OUTPUT
        else
          echo "result=passed" >> $GITHUB_OUTPUT
        fi

        if [ $CHECK_EXIT -eq 0 ]; then
          echo "::notice::Bellwether check passed - no drift detected"
        elif [ $CHECK_EXIT -eq 1 ]; then
          echo "::notice::Bellwether check: info-level changes detected (non-breaking)"
        elif [ $CHECK_EXIT -eq 2 ]; then
          echo "::warning::Bellwether check: warning-level changes detected"
        elif [ $CHECK_EXIT -eq 3 ]; then
          echo "::error::Bellwether check: breaking changes detected"
          echo ""
          echo "If changes are intentional, update your baseline:"
          echo "  bellwether baseline accept --reason \"Your reason here\" --force"
        elif [ $CHECK_EXIT -eq 5 ]; then
          echo "::warning::Bellwether check failed: low confidence metrics"
        else
          echo "::error::Bellwether check failed with error. Review the output above for details."
        fi

        if [ "$SHOULD_FAIL" = "true" ]; then
          exit $CHECK_EXIT
        fi
        exit 0

    - name: Upload CONTRACT.md artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-docs
        path: ${{ env.BELLWETHER_CONTRACT_PATH }}
        if-no-files-found: ignore

    - name: Upload baseline artifact
      if: inputs.save-baseline == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-baseline
        path: ${{ env.BELLWETHER_BASELINE_PATH }}
        if-no-files-found: ignore

    - name: Upload JSON report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-report
        path: ${{ env.BELLWETHER_CHECK_REPORT_PATH }}
        if-no-files-found: ignore

    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.upload-sarif == 'true' && always() && steps.test.outputs.sarif-file != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.test.outputs.sarif-file }}
        category: bellwether-mcp-check
      continue-on-error: true

    - name: Upload JUnit artifact
      if: inputs.format == 'junit' && always() && steps.test.outputs.junit-file != ''
      uses: actions/upload-artifact@v4
      with:
        name: bellwether-junit
        path: ${{ steps.test.outputs.junit-file }}
        if-no-files-found: ignore
