# GitLab CI Configuration for Bellwether
# Save as .gitlab-ci.yml in your repository root

stages:
  - test
  - security
  - report

variables:
  NODE_VERSION: "20"

# Base job template
.bellwether-base:
  image: node:${NODE_VERSION}
  before_script:
    - npm ci
    - npm install -g @dotsetlabs/bellwether

# Main behavioral testing job
bellwether-interview:
  extends: .bellwether-base
  stage: test
  script:
    - |
      bellwether interview \
        --ci \
        --baseline-file ./baseline.json \
        --fail-on-drift \
        -o ./bellwether-results \
        npx your-mcp-server
  artifacts:
    when: always
    paths:
      - bellwether-results/
    reports:
      junit: bellwether-results/junit.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Security-focused testing
security-audit:
  extends: .bellwether-base
  stage: security
  script:
    - |
      bellwether interview \
        --ci \
        --persona security_tester \
        --fail-on-security \
        --output sarif \
        -o ./security-results \
        npx your-mcp-server
  artifacts:
    when: always
    paths:
      - security-results/
    reports:
      # GitLab SAST integration
      sast: security-results/bellwether.sarif
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: false

# Update baseline on main branch
update-baseline:
  extends: .bellwether-base
  stage: report
  script:
    - |
      bellwether interview \
        --save-baseline ./baseline.json \
        npx your-mcp-server
    - |
      git config user.name "GitLab CI"
      git config user.email "ci@gitlab.com"
      git add baseline.json
      git diff --staged --quiet || git commit -m "chore: update bellwether baseline [skip ci]"
      git push "https://oauth2:${CI_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:${CI_COMMIT_REF_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
  needs:
    - bellwether-interview

# Generate HTML report
generate-report:
  extends: .bellwether-base
  stage: report
  script:
    - |
      bellwether interview \
        --output html \
        -o ./report \
        npx your-mcp-server
  artifacts:
    when: always
    paths:
      - report/
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: bellwether-report
    url: $CI_PAGES_URL

# Scheduled weekly drift detection
scheduled-audit:
  extends: .bellwether-base
  stage: test
  script:
    - |
      bellwether interview \
        --ci \
        --baseline-file ./baseline.json \
        --fail-on-drift \
        --persona technical_writer,security_tester,qa_engineer \
        -o ./audit-results \
        npx your-mcp-server
  artifacts:
    when: always
    paths:
      - audit-results/
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
